workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - tokens
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - flutter emulators --launch apple_ios_simulator
      - flutter packages pub get
      - 'flutter '
      - name: Dart Code Metrics
        script: |
          mkdir -p metrics-results
          flutter pub run dart_code_metrics:metrics analyze lib --reporter=json > metrics-results/dart_code_metrics.json      
        test_report: metrics-results/dart_code_metrics.json
      - name: Unit tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json      
        test_report: test-results/flutter.json
      - name: Coverage Test
        script: |
          #!/bin/bash
          flutter test --coverage
          bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN    
    artifacts:
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - hannahmilton@live.co.uk